# Generated by Django 4.0.3 on 2022-04-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundaHorarioAbertura', models.TimeField(blank=True, null=True)),
                ('segundaHorarioFechamento', models.TimeField(blank=True, null=True)),
                ('tercaHorarioAbertura', models.TimeField(blank=True, null=True)),
                ('tercaHorarioFechamento', models.TimeField(blank=True, null=True)),
                ('quartaHorarioAbertura', models.TimeField(blank=True, null=True)),
                ('quartaHorarioFechamento', models.TimeField(blank=True, null=True)),
                ('quintaHorarioAbertura', models.TimeField(blank=True, null=True)),
                ('quintaHorarioFechamento', models.TimeField(blank=True, null=True)),
                ('sextaHorarioAbertura', models.TimeField(blank=True, null=True)),
                ('sextaHorarioFechamento', models.TimeField(blank=True, null=True)),
                ('sabadoHorarioAbertura', models.TimeField(blank=True, null=True)),
                ('sabadoHorarioFechamento', models.TimeField(blank=True, null=True)),
                ('domingoHorarioAbertura', models.TimeField(blank=True, null=True)),
                ('domingoHorarioFechamento', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('razao_social', models.CharField(max_length=60, unique=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('whatsapp', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('plantonista', models.BooleanField()),
                ('url_image', models.URLField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=60, null=True)),
                ('horarioSemanal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encontraFarma.horariosemanal')),
            ],
        ),
    ]
